version: '3'
services:
  mongo-server:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
  node-app:
    build: .
    ports:
      - "4000:4000"
  easyenv:
    build: '../'
    ports:
      - "80:80"